# PyMOL Force Visualization Script
# Generated by MLFF Distiller

load molecule_with_H.pdb
hide everything
show sticks
show spheres
set sphere_scale, 0.3
set stick_radius, 0.15

# Color atoms by element
color white, elem H
color gray50, elem C
color blue, elem N
color red, elem O
color yellow, elem S
color orange, elem P

from pymol.cgo import *
from pymol import cmd

# Teacher Force Vectors (Orb-v2) - BLUE
teacher_forces = [
    BEGIN, LINES,
    COLOR, 0.2, 0.4, 1.0,  # Blue
    VERTEX, -2.2556, 2.7157, 3.5442,
    VERTEX, -2.4274, 2.7648, 3.6297,
    VERTEX, -0.7703, -1.8080, -0.7677,
    VERTEX, -0.7862, -1.7973, -0.7433,
    VERTEX, -1.4633, -2.2934, 0.5219,
    VERTEX, -1.4587, -2.3068, 0.5162,
    VERTEX, -0.3835, -5.0754, -3.4581,
    VERTEX, -0.3677, -5.1103, -3.4647,
    VERTEX, -1.2458, -2.9477, -2.8616,
    VERTEX, -1.2796, -2.8923, -2.8629,
    VERTEX, 1.1601, 4.0772, 3.2199,
    VERTEX, 1.1290, 4.4021, 3.3530,
    VERTEX, 0.0170, 3.4172, 3.1220,
    VERTEX, -0.0697, 3.3356, 3.2945,
    VERTEX, -0.9754, 1.5891, 1.8767,
    VERTEX, -0.7745, 1.4332, 1.8456,
    VERTEX, -1.2004, 3.5619, 3.8674,
    VERTEX, -1.1415, 3.7573, 3.9566,
    VERTEX, -0.5015, -2.9301, -1.7004,
    VERTEX, -0.5327, -2.9225, -1.7089,
    VERTEX, -1.2009, -3.9942, -3.7250,
    VERTEX, -1.2226, -4.0272, -3.7856,
    VERTEX, 1.4009, 2.6366, 1.5407,
    VERTEX, 1.3931, 2.4387, 1.2007,
    VERTEX, 0.4377, -0.9044, -0.5692,
    VERTEX, 0.4745, -0.8853, -0.6021,
    VERTEX, 1.9607, 3.6003, 2.2733,
    VERTEX, 2.3176, 3.7669, 2.2859,
    VERTEX, -0.3170, 1.3156, -1.0580,
    VERTEX, -0.3198, 1.4663, -1.1764,
    VERTEX, 0.4084, -5.0554, -2.3123,
    VERTEX, 0.4248, -5.0843, -2.3199,
    VERTEX, -2.1468, 1.7401, 2.5657,
    VERTEX, -2.3672, 1.6558, 2.4451,
    VERTEX, -0.7768, 0.5023, 0.9861,
    VERTEX, -0.8284, 0.4787, 0.9804,
    VERTEX, 0.1319, 2.4795, 2.1066,
    VERTEX, 0.0656, 2.3876, 2.0132,
    VERTEX, 0.3579, -3.9741, -1.4456,
    VERTEX, 0.3885, -3.9906, -1.4129,
    VERTEX, 1.2974, -0.7746, -1.8829,
    VERTEX, 1.2848, -0.7676, -1.8569,
    VERTEX, -0.2218, 0.4693, -0.2444,
    VERTEX, -0.1792, 0.3387, -0.1812,
    VERTEX, -2.5234, 2.1905, 4.4729,
    VERTEX, -2.5698, 2.2089, 4.4814,
    VERTEX, -2.9777, 3.4123, 3.0934,
    VERTEX, -3.0293, 3.4082, 3.1329,
    VERTEX, -1.5058, -1.1405, -1.2404,
    VERTEX, -1.5091, -1.1457, -1.2580,
    VERTEX, -0.9178, -1.9113, 1.3974,
    VERTEX, -0.9186, -1.9353, 1.4059,
    VERTEX, -2.4984, -1.9219, 0.5440,
    VERTEX, -2.4988, -1.9255, 0.5504,
    VERTEX, -1.4679, -3.3932, 0.5440,
    VERTEX, -1.4705, -3.3888, 0.5510,
    VERTEX, -0.3584, -5.9385, -4.1396,
    VERTEX, -0.3580, -5.9279, -4.1313,
    VERTEX, -1.8938, -2.0898, -3.0944,
    VERTEX, -1.8867, -2.0982, -3.0929,
    VERTEX, 1.0014, 5.0846, 3.0757,
    VERTEX, 1.0133, 5.0948, 3.0865,
    VERTEX, 0.3788, 2.6818, 3.8556,
    VERTEX, 0.3963, 2.6327, 3.9231,
    VERTEX, -0.5675, 0.9872, 2.7021,
    VERTEX, -0.5608, 0.9250, 2.7582,
    VERTEX, -1.5517, 4.5949, 3.7274,
    VERTEX, -1.5488, 4.6155, 3.7570,
    VERTEX, -0.9309, 3.2923, 4.8992,
    VERTEX, -0.9254, 3.3366, 4.9214,
    VERTEX, -1.8154, -3.9813, -4.6372,
    VERTEX, -1.8076, -3.9837, -4.6292,
    VERTEX, 1.3245, 2.9406, 0.4863,
    VERTEX, 1.3242, 2.9343, 0.4632,
    VERTEX, 1.9862, 1.7053, 1.5455,
    VERTEX, 1.9859, 1.6906, 1.5304,
    VERTEX, 1.1237, -1.2826, 0.2030,
    VERTEX, 1.1153, -1.2826, 0.2167,
    VERTEX, 2.2414, 4.4276, 1.6049,
    VERTEX, 2.2801, 4.4349, 1.6056,
    VERTEX, 2.8326, 3.1588, 2.7782,
    VERTEX, 2.8766, 3.1748, 2.7740,
    VERTEX, 1.0769, -5.9013, -2.0940,
    VERTEX, 1.0682, -5.8902, -2.0984,
    VERTEX, -2.3543, 0.7765, 3.0539,
    VERTEX, -2.3947, 0.7589, 3.0251,
    VERTEX, -2.8525, 2.0783, 1.7926,
    VERTEX, -2.9040, 2.0407, 1.7810,
    VERTEX, -1.1096, -0.4081, 1.3344,
    VERTEX, -1.0964, -0.3683, 1.3381,
    VERTEX, 0.5621, 1.7605, 2.8193,
    VERTEX, 0.6065, 1.7156, 2.8414,
    VERTEX, 1.0040, -3.9510, -0.5556,
    VERTEX, 0.9973, -3.9518, -0.5650,
    VERTEX, 2.3526, -0.6153, -1.6163,
    VERTEX, 2.3482, -0.6146, -1.6225,
    VERTEX, 1.2040, -1.6970, -2.4749,
    VERTEX, 1.2169, -1.6899, -2.4735,
    VERTEX, 0.9358, 0.0791, -2.4749,
    VERTEX, 0.9390, 0.0756, -2.4767,
    END
]
cmd.load_cgo(teacher_forces, 'teacher_forces')

# Student Force Vectors (PaiNN) - RED
student_forces = [
    BEGIN, LINES,
    COLOR, 1.0, 0.2, 0.2,  # Red
    VERTEX, -2.2556, 2.7157, 3.5442,
    VERTEX, -2.4301, 2.7571, 3.6281,
    VERTEX, -0.7703, -1.8080, -0.7677,
    VERTEX, -0.7825, -1.8122, -0.7404,
    VERTEX, -1.4633, -2.2934, 0.5219,
    VERTEX, -1.4559, -2.3087, 0.5129,
    VERTEX, -0.3835, -5.0754, -3.4581,
    VERTEX, -0.3673, -5.1061, -3.4601,
    VERTEX, -1.2458, -2.9477, -2.8616,
    VERTEX, -1.2752, -2.8905, -2.8654,
    VERTEX, 1.1601, 4.0772, 3.2199,
    VERTEX, 1.1412, 4.4295, 3.3565,
    VERTEX, 0.0170, 3.4172, 3.1220,
    VERTEX, -0.0608, 3.3257, 3.3046,
    VERTEX, -0.9754, 1.5891, 1.8767,
    VERTEX, -0.7784, 1.4236, 1.8301,
    VERTEX, -1.2004, 3.5619, 3.8674,
    VERTEX, -1.1375, 3.7584, 3.9457,
    VERTEX, -0.5015, -2.9301, -1.7004,
    VERTEX, -0.5401, -2.9189, -1.7035,
    VERTEX, -1.2009, -3.9942, -3.7250,
    VERTEX, -1.2230, -4.0309, -3.7887,
    VERTEX, 1.4009, 2.6366, 1.5407,
    VERTEX, 1.3914, 2.4471, 1.1885,
    VERTEX, 0.4377, -0.9044, -0.5692,
    VERTEX, 0.4639, -0.8669, -0.6144,
    VERTEX, 1.9607, 3.6003, 2.2733,
    VERTEX, 2.3200, 3.7687, 2.2862,
    VERTEX, -0.3170, 1.3156, -1.0580,
    VERTEX, -0.3187, 1.4640, -1.1911,
    VERTEX, 0.4084, -5.0554, -2.3123,
    VERTEX, 0.4227, -5.0859, -2.3198,
    VERTEX, -2.1468, 1.7401, 2.5657,
    VERTEX, -2.3554, 1.6610, 2.4455,
    VERTEX, -0.7768, 0.5023, 0.9861,
    VERTEX, -0.8417, 0.4610, 0.9788,
    VERTEX, 0.1319, 2.4795, 2.1066,
    VERTEX, 0.0740, 2.3779, 2.0232,
    VERTEX, 0.3579, -3.9741, -1.4456,
    VERTEX, 0.3926, -3.9953, -1.4189,
    VERTEX, 1.2974, -0.7746, -1.8829,
    VERTEX, 1.2842, -0.7675, -1.8547,
    VERTEX, -0.2218, 0.4693, -0.2444,
    VERTEX, -0.1695, 0.3477, -0.1644,
    VERTEX, -2.5234, 2.1905, 4.4729,
    VERTEX, -2.5640, 2.2111, 4.4800,
    VERTEX, -2.9777, 3.4123, 3.0934,
    VERTEX, -3.0269, 3.4059, 3.1357,
    VERTEX, -1.5058, -1.1405, -1.2404,
    VERTEX, -1.5076, -1.1405, -1.2565,
    VERTEX, -0.9178, -1.9113, 1.3974,
    VERTEX, -0.9227, -1.9369, 1.4067,
    VERTEX, -2.4984, -1.9219, 0.5440,
    VERTEX, -2.4996, -1.9290, 0.5517,
    VERTEX, -1.4679, -3.3932, 0.5440,
    VERTEX, -1.4739, -3.3879, 0.5554,
    VERTEX, -0.3584, -5.9385, -4.1396,
    VERTEX, -0.3585, -5.9267, -4.1302,
    VERTEX, -1.8938, -2.0898, -3.0944,
    VERTEX, -1.8864, -2.0994, -3.0899,
    VERTEX, 1.0014, 5.0846, 3.0757,
    VERTEX, 1.0154, 5.0984, 3.0942,
    VERTEX, 0.3788, 2.6818, 3.8556,
    VERTEX, 0.3780, 2.6197, 3.9255,
    VERTEX, -0.5675, 0.9872, 2.7021,
    VERTEX, -0.5634, 0.9259, 2.7546,
    VERTEX, -1.5517, 4.5949, 3.7274,
    VERTEX, -1.5503, 4.6195, 3.7561,
    VERTEX, -0.9309, 3.2923, 4.8992,
    VERTEX, -0.9291, 3.3382, 4.9293,
    VERTEX, -1.8154, -3.9813, -4.6372,
    VERTEX, -1.8065, -3.9836, -4.6257,
    VERTEX, 1.3245, 2.9406, 0.4863,
    VERTEX, 1.3267, 2.9358, 0.4629,
    VERTEX, 1.9862, 1.7053, 1.5455,
    VERTEX, 1.9843, 1.6958, 1.5293,
    VERTEX, 1.1237, -1.2826, 0.2030,
    VERTEX, 1.1188, -1.2881, 0.2147,
    VERTEX, 2.2414, 4.4276, 1.6049,
    VERTEX, 2.2797, 4.4352, 1.6002,
    VERTEX, 2.8326, 3.1588, 2.7782,
    VERTEX, 2.8735, 3.1740, 2.7769,
    VERTEX, 1.0769, -5.9013, -2.0940,
    VERTEX, 1.0684, -5.8916, -2.0976,
    VERTEX, -2.3543, 0.7765, 3.0539,
    VERTEX, -2.3953, 0.7603, 3.0243,
    VERTEX, -2.8525, 2.0783, 1.7926,
    VERTEX, -2.9015, 2.0402, 1.7838,
    VERTEX, -1.1096, -0.4081, 1.3344,
    VERTEX, -1.1046, -0.3554, 1.3390,
    VERTEX, 0.5621, 1.7605, 2.8193,
    VERTEX, 0.5971, 1.7061, 2.8402,
    VERTEX, 1.0040, -3.9510, -0.5556,
    VERTEX, 1.0016, -3.9539, -0.5612,
    VERTEX, 2.3526, -0.6153, -1.6163,
    VERTEX, 2.3526, -0.6169, -1.6215,
    VERTEX, 1.2040, -1.6970, -2.4749,
    VERTEX, 1.2151, -1.6869, -2.4754,
    VERTEX, 0.9358, 0.0791, -2.4749,
    VERTEX, 0.9372, 0.0778, -2.4792,
    END
]
cmd.load_cgo(student_forces, 'student_forces')

# Force Difference Vectors (Student - Teacher) - GREEN
force_errors = [
    BEGIN, LINES,
    COLOR, 0.2, 1.0, 0.2,  # Green
    VERTEX, -2.4274, 2.7648, 3.6297,
    VERTEX, -2.4301, 2.7571, 3.6281,
    VERTEX, -0.7862, -1.7973, -0.7433,
    VERTEX, -0.7825, -1.8122, -0.7404,
    VERTEX, -1.4587, -2.3068, 0.5162,
    VERTEX, -1.4559, -2.3087, 0.5129,
    VERTEX, -0.3677, -5.1103, -3.4647,
    VERTEX, -0.3673, -5.1061, -3.4601,
    VERTEX, -1.2796, -2.8923, -2.8629,
    VERTEX, -1.2752, -2.8905, -2.8654,
    VERTEX, 1.1290, 4.4021, 3.3530,
    VERTEX, 1.1412, 4.4295, 3.3565,
    VERTEX, -0.0697, 3.3356, 3.2945,
    VERTEX, -0.0608, 3.3257, 3.3046,
    VERTEX, -0.7745, 1.4332, 1.8456,
    VERTEX, -0.7784, 1.4236, 1.8301,
    VERTEX, -1.1415, 3.7573, 3.9566,
    VERTEX, -1.1375, 3.7584, 3.9457,
    VERTEX, -0.5327, -2.9225, -1.7089,
    VERTEX, -0.5401, -2.9189, -1.7035,
    VERTEX, -1.2226, -4.0272, -3.7856,
    VERTEX, -1.2230, -4.0309, -3.7887,
    VERTEX, 1.3931, 2.4387, 1.2007,
    VERTEX, 1.3914, 2.4471, 1.1885,
    VERTEX, 0.4745, -0.8853, -0.6021,
    VERTEX, 0.4639, -0.8669, -0.6144,
    VERTEX, 2.3176, 3.7669, 2.2859,
    VERTEX, 2.3200, 3.7687, 2.2862,
    VERTEX, -0.3198, 1.4663, -1.1764,
    VERTEX, -0.3187, 1.4640, -1.1911,
    VERTEX, 0.4248, -5.0843, -2.3199,
    VERTEX, 0.4227, -5.0859, -2.3198,
    VERTEX, -2.3672, 1.6558, 2.4451,
    VERTEX, -2.3554, 1.6610, 2.4455,
    VERTEX, -0.8284, 0.4787, 0.9804,
    VERTEX, -0.8417, 0.4610, 0.9788,
    VERTEX, 0.0656, 2.3876, 2.0132,
    VERTEX, 0.0740, 2.3779, 2.0232,
    VERTEX, 0.3885, -3.9906, -1.4129,
    VERTEX, 0.3926, -3.9953, -1.4189,
    VERTEX, 1.2848, -0.7676, -1.8569,
    VERTEX, 1.2842, -0.7675, -1.8547,
    VERTEX, -0.1792, 0.3387, -0.1812,
    VERTEX, -0.1695, 0.3477, -0.1644,
    VERTEX, -2.5698, 2.2089, 4.4814,
    VERTEX, -2.5640, 2.2111, 4.4800,
    VERTEX, -3.0293, 3.4082, 3.1329,
    VERTEX, -3.0269, 3.4059, 3.1357,
    VERTEX, -1.5091, -1.1457, -1.2580,
    VERTEX, -1.5076, -1.1405, -1.2565,
    VERTEX, -0.9186, -1.9353, 1.4059,
    VERTEX, -0.9227, -1.9369, 1.4067,
    VERTEX, -2.4988, -1.9255, 0.5504,
    VERTEX, -2.4996, -1.9290, 0.5517,
    VERTEX, -1.4705, -3.3888, 0.5510,
    VERTEX, -1.4739, -3.3879, 0.5554,
    VERTEX, -0.3580, -5.9279, -4.1313,
    VERTEX, -0.3585, -5.9267, -4.1302,
    VERTEX, -1.8867, -2.0982, -3.0929,
    VERTEX, -1.8864, -2.0994, -3.0899,
    VERTEX, 1.0133, 5.0948, 3.0865,
    VERTEX, 1.0154, 5.0984, 3.0942,
    VERTEX, 0.3963, 2.6327, 3.9231,
    VERTEX, 0.3780, 2.6197, 3.9255,
    VERTEX, -0.5608, 0.9250, 2.7582,
    VERTEX, -0.5634, 0.9259, 2.7546,
    VERTEX, -1.5488, 4.6155, 3.7570,
    VERTEX, -1.5503, 4.6195, 3.7561,
    VERTEX, -0.9254, 3.3366, 4.9214,
    VERTEX, -0.9291, 3.3382, 4.9293,
    VERTEX, -1.8076, -3.9837, -4.6292,
    VERTEX, -1.8065, -3.9836, -4.6257,
    VERTEX, 1.3242, 2.9343, 0.4632,
    VERTEX, 1.3267, 2.9358, 0.4629,
    VERTEX, 1.9859, 1.6906, 1.5304,
    VERTEX, 1.9843, 1.6958, 1.5293,
    VERTEX, 1.1153, -1.2826, 0.2167,
    VERTEX, 1.1188, -1.2881, 0.2147,
    VERTEX, 2.2801, 4.4349, 1.6056,
    VERTEX, 2.2797, 4.4352, 1.6002,
    VERTEX, 2.8766, 3.1748, 2.7740,
    VERTEX, 2.8735, 3.1740, 2.7769,
    VERTEX, 1.0682, -5.8902, -2.0984,
    VERTEX, 1.0684, -5.8916, -2.0976,
    VERTEX, -2.3947, 0.7589, 3.0251,
    VERTEX, -2.3953, 0.7603, 3.0243,
    VERTEX, -2.9040, 2.0407, 1.7810,
    VERTEX, -2.9015, 2.0402, 1.7838,
    VERTEX, -1.0964, -0.3683, 1.3381,
    VERTEX, -1.1046, -0.3554, 1.3390,
    VERTEX, 0.6065, 1.7156, 2.8414,
    VERTEX, 0.5971, 1.7061, 2.8402,
    VERTEX, 0.9973, -3.9518, -0.5650,
    VERTEX, 1.0016, -3.9539, -0.5612,
    VERTEX, 2.3482, -0.6146, -1.6225,
    VERTEX, 2.3526, -0.6169, -1.6215,
    VERTEX, 1.2169, -1.6899, -2.4735,
    VERTEX, 1.2151, -1.6869, -2.4754,
    VERTEX, 0.9390, 0.0756, -2.4767,
    VERTEX, 0.9372, 0.0778, -2.4792,
    END
]
cmd.load_cgo(force_errors, 'force_errors')

# Label atoms with largest force errors
cmd.label('id 22', '"Err: 0.524 eV/Å"')
cmd.label('id 18', '"Err: 0.545 eV/Å"')
cmd.label('id 32', '"Err: 0.553 eV/Å"')
cmd.label('id 13', '"Err: 0.603 eV/Å"')
cmd.label('id 6', '"Err: 0.742 eV/Å"')

# Visualization settings
set label_size, 20
set label_color, yellow
bg_color white
set line_width, 3

# Create groups for easy toggling
group teacher, teacher_forces
group student, student_forces
group errors, force_errors

# Set up view
orient
zoom
center

# Force Statistics
# Force scale factor: 0.0407 Angstrom/(eV/Angstrom)
# Teacher max force: 9.684 eV/Å
# Student max force: 9.829 eV/Å
# Max force error: 0.742 eV/Å
# Mean force error: 0.218 eV/Å

# USAGE INSTRUCTIONS:
# - Blue arrows = Teacher (Orb-v2) forces
# - Red arrows = Student (PaiNN) forces
# - Green arrows = Error vectors (Student - Teacher)
#
# Toggle visibility:
#   disable teacher    # Hide teacher forces
#   enable teacher     # Show teacher forces
#   disable student    # Hide student forces
#   enable student     # Show student forces
#   disable errors     # Hide error vectors
#   enable errors      # Show error vectors
#
# Compare predictions:
#   disable errors; enable teacher; enable student
#
# View only errors:
#   disable teacher; disable student; enable errors
