#!/usr/bin/env python
"""
Validate Generative Model Test Structures with Orb-v2

This script validates that structures generated by MatterGen and MolDiff
can be successfully labeled by the orb-v2 teacher model.

Usage:
    python scripts/validate_generative_test.py
"""

import sys
from pathlib import Path

import numpy as np
from ase.io import read

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / 'src'))

from mlff_distiller.models.teacher_wrappers import OrbCalculator


def validate_structures(structures_path, name):
    """Validate structures can be labeled by orb-v2."""
    print(f"\n{'='*60}")
    print(f"Validating {name}")
    print(f"{'='*60}")

    # Load structures
    if structures_path.suffix == '.extxyz':
        structures = read(str(structures_path), index=':')
    elif structures_path.is_dir():
        # Load all SDF files from directory
        structures = []
        for sdf_file in sorted(structures_path.glob('*.sdf')):
            try:
                mol = read(str(sdf_file))
                structures.append(mol)
            except Exception as e:
                print(f"  [WARN] Failed to load {sdf_file.name}: {e}")
    else:
        structures = [read(str(structures_path))]

    print(f"Loaded {len(structures)} structures")

    # Initialize orb-v2 calculator
    print("Initializing orb-v2 calculator...")
    calc = OrbCalculator(model_name="orb-v2", device="cuda")

    # Validate each structure
    success_count = 0
    for i, atoms in enumerate(structures):
        try:
            atoms.calc = calc
            energy = atoms.get_potential_energy()
            forces = atoms.get_forces()

            # Check for NaN or Inf
            if np.isnan(energy) or np.isinf(energy):
                print(f"  [{i}] FAILED: Invalid energy value")
                continue
            if np.any(np.isnan(forces)) or np.any(np.isinf(forces)):
                print(f"  [{i}] FAILED: Invalid force values")
                continue

            print(f"  [{i}] SUCCESS: E={energy:.3f} eV, |F|_max={np.abs(forces).max():.3f} eV/Å")
            success_count += 1

        except Exception as e:
            print(f"  [{i}] FAILED: {str(e)[:80]}")

    print(f"\nResults: {success_count}/{len(structures)} structures validated ({100*success_count/len(structures):.1f}%)")

    return success_count, len(structures)


def main():
    """Main validation script."""
    project_root = Path(__file__).parent.parent

    # Validate MatterGen crystals
    mattergen_path = project_root / "data/generative_test/mattergen/generated_crystals.extxyz"
    mattergen_success, mattergen_total = validate_structures(mattergen_path, "MatterGen Crystals")

    # Validate MolDiff molecules
    moldiff_dir = list((project_root / "data/generative_test/moldiff").glob("*_SDF"))[0]
    moldiff_success, moldiff_total = validate_structures(moldiff_dir, "MolDiff Molecules")

    # Summary
    total_success = mattergen_success + moldiff_success
    total_structures = mattergen_total + moldiff_total

    print(f"\n{'='*60}")
    print(f"OVERALL VALIDATION SUMMARY")
    print(f"{'='*60}")
    print(f"Total structures validated: {total_success}/{total_structures} ({100*total_success/total_structures:.1f}%)")
    print(f"  MatterGen (crystals):    {mattergen_success}/{mattergen_total} ({100*mattergen_success/mattergen_total:.1f}%)")
    print(f"  MolDiff (molecules):     {moldiff_success}/{moldiff_total} ({100*moldiff_success/moldiff_total:.1f}%)")

    # Go/No-Go decision
    print(f"\n{'='*60}")
    print(f"GO/NO-GO DECISION")
    print(f"{'='*60}")

    success_rate = 100 * total_success / total_structures
    if success_rate >= 95:
        print(f"✓ GO: {success_rate:.1f}% success rate (target: ≥95%)")
        print("  Generative models produce valid structures for teacher labeling.")
        print("  Recommend proceeding with hybrid generative approach for 120K dataset.")
    elif success_rate >= 80:
        print(f"⚠ CONDITIONAL GO: {success_rate:.1f}% success rate")
        print("  Acceptable but below target. Consider:")
        print("  - Using only successful structures")
        print("  - Adjusting generative model parameters")
        print("  - Supplementing with more traditional data")
    else:
        print(f"✗ NO-GO: {success_rate:.1f}% success rate (target: ≥95%)")
        print("  Too many invalid structures. Recommend:")
        print("  - Debugging generative model outputs")
        print("  - Falling back to traditional data generation")
        print("  - Investigating why orb-v2 rejects these structures")

    print(f"{'='*60}\n")


if __name__ == '__main__':
    main()
