#!/usr/bin/env python3
"""
Visualize Force Predictions with PyMOL

This script creates PyMOL visualizations comparing teacher and student force
predictions on a test molecule with explicit hydrogens. Force vectors are
displayed as arrows centered on each atom with appropriate scaling.

Usage:
    python scripts/visualize_forces_pymol.py \
        --checkpoint checkpoints/best_model.pt \
        --test-molecule data/generative_test/moldiff/test_10mols_20251123_181225_SDF/0.sdf \
        --output-dir visualizations/forces

Author: ML Distillation Project
Date: 2025-11-24
"""

import sys
import argparse
from pathlib import Path
import logging

import numpy as np
import torch
from ase.io import write as ase_write

# Add src to path
REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / 'src'))

from mlff_distiller.data.sdf_utils import read_structure_with_hydrogen_support, check_hydrogen_content
from mlff_distiller.models.teacher_wrappers import OrbCalculator
from mlff_distiller.models.student_model import StudentForceField


def setup_logging():
    """Setup logging configuration."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )
    return logging.getLogger(__name__)


def load_student_model(checkpoint_path: Path, device: str):
    """Load student model from checkpoint."""
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)

    # Create model with same architecture as training
    model = StudentForceField(
        hidden_dim=128,
        num_interactions=3,
        num_rbf=20,
        cutoff=5.0,
        max_z=100
    ).to(device)

    # Load weights - handle "model." prefix from DistillationWrapper
    state_dict = checkpoint['model_state_dict']
    if any(k.startswith('model.') for k in state_dict.keys()):
        state_dict = {k.replace('model.', ''): v for k, v in state_dict.items()}

    model.load_state_dict(state_dict)
    model.eval()

    return model


def predict_with_student(model, atoms, device: str):
    """Get predictions from student model."""
    atomic_numbers = torch.tensor(atoms.get_atomic_numbers(), dtype=torch.long, device=device)
    positions = torch.tensor(atoms.get_positions(), dtype=torch.float32, device=device)
    positions.requires_grad_(True)

    batch = torch.zeros(len(atomic_numbers), dtype=torch.long, device=device)

    energy = model(atomic_numbers, positions, cell=None, pbc=None, batch=batch)

    forces = -torch.autograd.grad(
        energy.sum(),
        positions,
        create_graph=False,
        retain_graph=False
    )[0]

    return energy.item(), forces.cpu().numpy()


def save_pymol_script(
    atoms,
    teacher_forces,
    student_forces,
    output_dir: Path,
    force_scale: float = 0.1,
    logger=None
):
    """
    Save PyMOL visualization script with force vectors.

    Args:
        atoms: ASE Atoms object with structure
        teacher_forces: Teacher force predictions (N, 3)
        student_forces: Student force predictions (N, 3)
        output_dir: Output directory for files
        force_scale: Scaling factor for force arrow length
        logger: Logger instance
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save structure as PDB for PyMOL
    structure_file = output_dir / "molecule_with_H.pdb"
    ase_write(str(structure_file), atoms, format='proteindatabank')

    if logger:
        logger.info(f"Saved structure to {structure_file}")

    # Get positions
    positions = atoms.get_positions()

    # Compute force statistics for scaling
    teacher_force_mags = np.linalg.norm(teacher_forces, axis=1)
    student_force_mags = np.linalg.norm(student_forces, axis=1)
    max_force = max(teacher_force_mags.max(), student_force_mags.max())

    # Auto-scale forces to be visible but not overwhelming
    # Target: largest force arrow should be ~2 Angstroms
    if max_force > 0:
        auto_scale = 2.0 / max_force
    else:
        auto_scale = 1.0

    scale = force_scale * auto_scale

    # Create PyMOL script
    script_file = output_dir / "visualize_forces.pml"

    with open(script_file, 'w') as f:
        f.write("# PyMOL Force Visualization Script\n")
        f.write("# Generated by MLFF Distiller\n\n")

        # Load structure
        f.write(f"load {structure_file.name}\n")
        f.write("hide everything\n")
        f.write("show sticks\n")
        f.write("show spheres\n")
        f.write("set sphere_scale, 0.3\n")
        f.write("set stick_radius, 0.15\n\n")

        # Color by element
        f.write("# Color atoms by element\n")
        f.write("color white, elem H\n")
        f.write("color gray50, elem C\n")
        f.write("color blue, elem N\n")
        f.write("color red, elem O\n")
        f.write("color yellow, elem S\n")
        f.write("color orange, elem P\n\n")

        # Create CGO objects for force vectors
        f.write("from pymol.cgo import *\n")
        f.write("from pymol import cmd\n\n")

        # Teacher forces (blue arrows)
        f.write("# Teacher Force Vectors (Orb-v2) - BLUE\n")
        f.write("teacher_forces = [\n")
        f.write("    BEGIN, LINES,\n")
        f.write("    COLOR, 0.2, 0.4, 1.0,  # Blue\n")

        for i, (pos, force) in enumerate(zip(positions, teacher_forces)):
            # Arrow from atom center
            start = pos
            end = pos + force * scale

            f.write(f"    VERTEX, {start[0]:.4f}, {start[1]:.4f}, {start[2]:.4f},\n")
            f.write(f"    VERTEX, {end[0]:.4f}, {end[1]:.4f}, {end[2]:.4f},\n")

        f.write("    END\n")
        f.write("]\n")
        f.write("cmd.load_cgo(teacher_forces, 'teacher_forces')\n\n")

        # Student forces (red arrows)
        f.write("# Student Force Vectors (PaiNN) - RED\n")
        f.write("student_forces = [\n")
        f.write("    BEGIN, LINES,\n")
        f.write("    COLOR, 1.0, 0.2, 0.2,  # Red\n")

        for i, (pos, force) in enumerate(zip(positions, student_forces)):
            # Arrow from atom center
            start = pos
            end = pos + force * scale

            f.write(f"    VERTEX, {start[0]:.4f}, {start[1]:.4f}, {start[2]:.4f},\n")
            f.write(f"    VERTEX, {end[0]:.4f}, {end[1]:.4f}, {end[2]:.4f},\n")

        f.write("    END\n")
        f.write("]\n")
        f.write("cmd.load_cgo(student_forces, 'student_forces')\n\n")

        # Force difference vectors (green arrows)
        f.write("# Force Difference Vectors (Student - Teacher) - GREEN\n")
        f.write("force_errors = [\n")
        f.write("    BEGIN, LINES,\n")
        f.write("    COLOR, 0.2, 1.0, 0.2,  # Green\n")

        for i, (pos, t_force, s_force) in enumerate(zip(positions, teacher_forces, student_forces)):
            # Difference arrow from teacher endpoint
            start = pos + t_force * scale
            diff = (s_force - t_force) * scale
            end = start + diff

            f.write(f"    VERTEX, {start[0]:.4f}, {start[1]:.4f}, {start[2]:.4f},\n")
            f.write(f"    VERTEX, {end[0]:.4f}, {end[1]:.4f}, {end[2]:.4f},\n")

        f.write("    END\n")
        f.write("]\n")
        f.write("cmd.load_cgo(force_errors, 'force_errors')\n\n")

        # Add labels for largest force errors
        f.write("# Label atoms with largest force errors\n")
        force_errors_mag = np.linalg.norm(student_forces - teacher_forces, axis=1)
        top_errors = np.argsort(force_errors_mag)[-5:]  # Top 5 errors

        for idx in top_errors:
            error_mag = force_errors_mag[idx]
            f.write(f"cmd.label('id {idx+1}', '\"Err: {error_mag:.3f} eV/Å\"')\n")

        f.write("\n# Visualization settings\n")
        f.write("set label_size, 20\n")
        f.write("set label_color, yellow\n")
        f.write("bg_color white\n")
        f.write("set line_width, 3\n\n")

        # Create groups for toggling
        f.write("# Create groups for easy toggling\n")
        f.write("group teacher, teacher_forces\n")
        f.write("group student, student_forces\n")
        f.write("group errors, force_errors\n\n")

        # Views
        f.write("# Set up view\n")
        f.write("orient\n")
        f.write("zoom\n")
        f.write("center\n\n")

        # Print statistics
        f.write("# Force Statistics\n")
        f.write(f"# Force scale factor: {scale:.4f} Angstrom/(eV/Angstrom)\n")
        f.write(f"# Teacher max force: {teacher_force_mags.max():.3f} eV/Å\n")
        f.write(f"# Student max force: {student_force_mags.max():.3f} eV/Å\n")
        f.write(f"# Max force error: {force_errors_mag.max():.3f} eV/Å\n")
        f.write(f"# Mean force error: {force_errors_mag.mean():.3f} eV/Å\n\n")

        # Usage instructions
        f.write("# USAGE INSTRUCTIONS:\n")
        f.write("# - Blue arrows = Teacher (Orb-v2) forces\n")
        f.write("# - Red arrows = Student (PaiNN) forces\n")
        f.write("# - Green arrows = Error vectors (Student - Teacher)\n")
        f.write("#\n")
        f.write("# Toggle visibility:\n")
        f.write("#   disable teacher    # Hide teacher forces\n")
        f.write("#   enable teacher     # Show teacher forces\n")
        f.write("#   disable student    # Hide student forces\n")
        f.write("#   enable student     # Show student forces\n")
        f.write("#   disable errors     # Hide error vectors\n")
        f.write("#   enable errors      # Show error vectors\n")
        f.write("#\n")
        f.write("# Compare predictions:\n")
        f.write("#   disable errors; enable teacher; enable student\n")
        f.write("#\n")
        f.write("# View only errors:\n")
        f.write("#   disable teacher; disable student; enable errors\n")

    if logger:
        logger.info(f"Saved PyMOL script to {script_file}")
        logger.info(f"\nTo visualize:")
        logger.info(f"  cd {output_dir}")
        logger.info(f"  pymol visualize_forces.pml")


def main():
    parser = argparse.ArgumentParser(
        description="Visualize force predictions with PyMOL"
    )
    parser.add_argument(
        '--checkpoint',
        type=Path,
        default=REPO_ROOT / 'checkpoints/best_model.pt',
        help='Path to student model checkpoint'
    )
    parser.add_argument(
        '--test-molecule',
        type=Path,
        default=REPO_ROOT / 'data/generative_test/moldiff/test_10mols_20251123_181225_SDF/0.sdf',
        help='Path to test molecule SDF file'
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        default=REPO_ROOT / 'visualizations/forces',
        help='Output directory for visualization files'
    )
    parser.add_argument(
        '--force-scale',
        type=float,
        default=0.1,
        help='Scaling factor for force arrow length (default: 0.1)'
    )
    parser.add_argument(
        '--device',
        type=str,
        default='cuda' if torch.cuda.is_available() else 'cpu',
        help='Device for inference'
    )

    args = parser.parse_args()
    logger = setup_logging()

    logger.info("=" * 80)
    logger.info("PyMOL Force Visualization")
    logger.info("=" * 80)
    logger.info(f"Checkpoint: {args.checkpoint}")
    logger.info(f"Test molecule: {args.test_molecule}")
    logger.info(f"Output directory: {args.output_dir}")
    logger.info(f"Device: {args.device}")

    # Load test molecule with explicit hydrogens
    logger.info("\nLoading test molecule with explicit hydrogens...")
    atoms = read_structure_with_hydrogen_support(args.test_molecule)
    h_stats = check_hydrogen_content(atoms)
    logger.info(f"✓ Loaded {h_stats['n_atoms']} atoms ({h_stats['h_percentage']:.1f}% hydrogen)")
    logger.info(f"  Formula: {atoms.get_chemical_formula()}")

    # Load teacher model
    logger.info("\nInitializing teacher model (Orb-v2)...")
    teacher = OrbCalculator(device=args.device)
    logger.info("✓ Teacher model loaded")

    # Load student model
    logger.info("\nLoading student model...")
    student = load_student_model(args.checkpoint, args.device)
    logger.info("✓ Student model loaded")

    # Get teacher predictions
    logger.info("\nGetting teacher predictions...")
    atoms.calc = teacher
    teacher_energy = atoms.get_potential_energy()
    teacher_forces = atoms.get_forces()
    logger.info("✓ Teacher predictions computed")

    # Get student predictions
    logger.info("\nGetting student predictions...")
    student_energy, student_forces = predict_with_student(student, atoms, args.device)
    logger.info("✓ Student predictions computed")

    # Compute error statistics
    force_errors = np.linalg.norm(student_forces - teacher_forces, axis=1)
    logger.info("\n" + "=" * 80)
    logger.info("FORCE STATISTICS")
    logger.info("=" * 80)
    logger.info(f"Teacher max force magnitude: {np.linalg.norm(teacher_forces, axis=1).max():.3f} eV/Å")
    logger.info(f"Student max force magnitude: {np.linalg.norm(student_forces, axis=1).max():.3f} eV/Å")
    logger.info(f"Mean force error: {force_errors.mean():.3f} eV/Å")
    logger.info(f"Max force error: {force_errors.max():.3f} eV/Å")
    logger.info(f"Median force error: {np.median(force_errors):.3f} eV/Å")

    # Save PyMOL visualization
    logger.info("\nCreating PyMOL visualization...")
    save_pymol_script(
        atoms,
        teacher_forces,
        student_forces,
        args.output_dir,
        force_scale=args.force_scale,
        logger=logger
    )

    logger.info("\n" + "=" * 80)
    logger.info("VISUALIZATION COMPLETE!")
    logger.info("=" * 80)
    logger.info(f"\nTo view the visualization:")
    logger.info(f"  cd {args.output_dir}")
    logger.info(f"  pymol visualize_forces.pml")
    logger.info("\nVisualization features:")
    logger.info("  - BLUE arrows: Teacher (Orb-v2) force predictions")
    logger.info("  - RED arrows: Student (PaiNN) force predictions")
    logger.info("  - GREEN arrows: Error vectors (Student - Teacher)")
    logger.info("  - Yellow labels: Top 5 atoms with largest force errors")
    logger.info("  - All hydrogens are shown explicitly")
    logger.info("\nUse PyMOL commands to toggle layers:")
    logger.info("  disable teacher  # Hide teacher forces")
    logger.info("  disable student  # Hide student forces")
    logger.info("  disable errors   # Hide error vectors")
    logger.info("=" * 80)

    return 0


if __name__ == '__main__':
    sys.exit(main())
